name: Tests

on:
    workflow_dispatch:
    pull_request:
        branches:
            - main
    workflow_call:

# Set default permissions for all jobs
permissions:
    contents: read # Needed to check out code
    checks: write # Needed to report test results
    pull-requests: write # Needed to add comments/annotations to PRs

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 20.15.1

            # Cache root dependencies - only reuse if package-lock.json exactly matches
            - name: Cache root dependencies
              uses: actions/cache@v4
              id: root-cache
              with:
                  path: node_modules
                  key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}

            # Cache webview-ui dependencies - only reuse if package-lock.json exactly matches
            - name: Cache webview-ui dependencies
              uses: actions/cache@v4
              id: webview-cache
              with:
                  path: webview-ui/node_modules
                  key: ${{ runner.os }}-npm-webview-${{ hashFiles('webview-ui/package-lock.json') }}

            - name: Install root dependencies
              if: steps.root-cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Install webview-ui dependencies
              if: steps.webview-cache.outputs.cache-hit != 'true'
              run: cd webview-ui && npm ci

            - name: Type Check
              run: npm run check-types

            - name: ESLint Check
              run: npm run lint

            - name: Prettier / Format Check
              run: npm run format

            - name: Extension Tests
              run: xvfb-run -a npm run test

    complexity-check:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 20.15.1

            - name: Install dependencies
              run: npm ci

            - name: Analyze Base Branch Complexity
              id: base-complexity
              run: |
                  git fetch origin ${{ github.base_ref }}
                  git checkout origin/${{ github.base_ref }}
                  npm run lint:complexity
                  BASE_VIOLATIONS=$(jq '.length' complexity-report.json || echo "0")
                  echo "base_violations=$BASE_VIOLATIONS" >> $GITHUB_OUTPUT

            - name: Analyze PR Branch Complexity
              id: pr-complexity
              run: |
                  git checkout ${{ github.head_ref }}
                  npm run lint:complexity
                  PR_VIOLATIONS=$(jq '.length' complexity-report.json || echo "0")
                  echo "pr_violations=$PR_VIOLATIONS" >> $GITHUB_OUTPUT

            - name: Compare Complexity
              if: ${{ steps.pr-complexity.outputs.pr_violations > steps.base-complexity.outputs.base_violations }}
              run: |
                  echo "::warning::Code complexity has increased in this PR"
                  echo "Base branch violations: ${{ steps.base-complexity.outputs.base_violations }}"
                  echo "PR branch violations: ${{ steps.pr-complexity.outputs.pr_violations }}"
                  
                  # Generate detailed report
                  echo "### Complexity Analysis Report" > complexity-report.md
                  echo "| Metric | Base Branch | PR Branch |" >> complexity-report.md
                  echo "|--------|-------------|-----------|" >> complexity-report.md
                  echo "| ESLint Complexity Violations | ${{ steps.base-complexity.outputs.base_violations }} | ${{ steps.pr-complexity.outputs.pr_violations }} |" >> complexity-report.md
                  
                  # Add PR comment with the report
                  gh pr comment ${{ github.event.pull_request.number }} --body-file complexity-report.md
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
